ap/ap/urls.py
# coding: utf-8
import django
from django.conf import settings
from django.conf.urls import include, url
from django.contrib.auth.views import login as auth_login, logout_then_login
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from .views import home, custom404errorview, custom500errorview, custom503errorview
from accounts.views import *
from audio.views import AudioRequestViewSet
from schedules.views import EventViewSet, ScheduleViewSet, AllEventViewSet, AllScheduleViewSet
from attendance.views import RollViewSet, AllRollViewSet, AttendanceViewSet, AllAttendanceViewSet
from leaveslips.views import IndividualSlipViewSet, GroupSlipViewSet, AllIndividualSlipViewSet, AllGroupSlipViewSet
from books.views import BooksViewSet
from lifestudies.views import DisciplineSummariesViewSet
from seating.views import ChartViewSet, SeatViewSet, PartialViewSet
from terms.views import TermViewSet
from services.views import UpdateWorkersViewSet, ServiceSlotWorkloadViewSet, ServiceActiveViewSet, AssignmentViewSet, AssignmentPinViewSet, ServiceTimeViewSet, ExceptionActiveViewSet
from meal_seating.views import TableViewSet
from web_access.forms import WebAccessRequestGuestCreateForm as form
from classnotes.views import ClassNoteViewSet

from rest_framework_swagger.views import get_swagger_view
from rest_framework_nested import routers
from rest_framework_bulk.routes import BulkRouter

from wiki.urls import get_pattern as get_wiki_pattern
from django_nyt.urls import get_pattern as get_nyt_pattern

admin.autodiscover()

urlpatterns = [
  url(r'^$', home, name='home'),
  url(r'^accounts/login/$', auth_login, {'extra_context': {'webaccess_form': form}}, name='login'),
  url(r'^accounts/logout/$', logout_then_login, name='logout'),
  url(r'^accounts/', include('accounts.urls')),
  url(r'^audio/', include('audio.urls', namespace='audio')),
  url(r'^dailybread/', include('dailybread.urls', namespace="dailybread")),
  url(r'^badges/', include('badges.urls', namespace="badges")),
  url(r'^schedules/', include('schedules.urls', namespace="schedules")),
  url(r'^attendance/', include('attendance.urls', namespace="attendance")),
  url(r'^leaveslips/', include('leaveslips.urls', namespace="leaveslips")),
  url(r'^verse_parse/', include('verse_parse.urls', namespace="verse_parse")),
  url(r'^meal_seating/', include('meal_seating.urls')),
  url(r'^absent_trainee_roster/', include('absent_trainee_roster.urls', namespace="absent_trainee_roster")),
  url(r'^syllabus/', include('syllabus.urls', namespace="syllabus")),
  url(r'^classnotes/', include('classnotes.urls', namespace="classnotes")),
  url(r'^classes/', include('classes.urls', namespace="classes")),
  url(r'^lifestudies/', include('lifestudies.urls', namespace="lifestudies")),
  url(r'^seating/', include('seating.urls', namespace='seating')),
  url(r'^exams/', include('exams.urls', namespace="exams")),
  url(r'^web_access/', include('web_access.urls', namespace="web_access")),
  url(r'^apimport/', include('apimport.urls', namespace="apimport")),
  url(r'^bible_tracker/', include('bible_tracker.urls', namespace='bible_tracker')),
  url(r'^announcements/', include('announcements.urls', namespace='announcements')),
  url(r'^services/', include('services.urls', namespace="services")),
  url(r'^semi/', include('semi.urls', namespace="semi")),
  url(r'^house_requests/', include('house_requests.urls', namespace="house_requests")),
  url(r'^hc/', include('hc.urls', namespace="hc")),
  url(r'^room_reservations/', include('room_reservations.urls', namespace="room_reservations")),
  url(r'^graduation/', include('graduation.urls', namespace="graduation")),
  url(r'^xb/', include('xb_application.urls', namespace="xb")),
  url(r'^interim/', include('interim.urls', namespace="interim")),
  # admin urls
  url(r'^adminactions/', include('adminactions.urls')),  # django-adminactions pluggable app
  url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
  url(r'^admin/', include(admin.site.urls)),
  url(r'^admin/', include("massadmin.urls")),
  url(r'^static/(?P<path>.*)$', django.views.static.serve, {'document_root': settings.STATIC_ROOT}),
  # fobi urls
  # DB Store plugin URLs
  url(r'^fobi/plugins/form-handlers/db-store/', include('fobi.contrib.plugins.form_handlers.db_store.urls')),
  url(r'^fobi/plugins/form-wizard-handlers/db-store/', include('fobi.contrib.plugins.form_handlers.db_store.urls.form_wizard_handlers')),
  # View URLs
  url(r'^forms/', include('fobi.urls.view')),
  # Edit URLs
  url(r'^forms/', include('fobi.urls.edit')),
  url(r'^404/$', custom404errorview),  # for development
  url(r'^500/$', custom500errorview),  # for development
  url(r'^503/$', custom503errorview),  # for development
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

router = BulkRouter()
router.register(r'users', UserViewSet)
router.register(r'trainees', TraineeViewSet, base_name='trainees')
router.register(r'events', EventViewSet)
router.register(r'allevents', AllEventViewSet, base_name='allevents')
router.register(r'schedules', ScheduleViewSet)
router.register(r'allschedules', AllScheduleViewSet, base_name='allschedules')
router.register(r'rolls', RollViewSet)
router.register(r'allrolls', AllRollViewSet, base_name='allrolls')
router.register(r'individualslips', IndividualSlipViewSet)
router.register(r'allindividualleaveslips', AllIndividualSlipViewSet, base_name='allindividualslips')
router.register(r'groupslips', GroupSlipViewSet)
router.register(r'allgroupslips', AllGroupSlipViewSet, base_name='allgroupslips')
router.register(r'books', BooksViewSet)
router.register(r'summaries', DisciplineSummariesViewSet)
router.register(r'attendance', AttendanceViewSet)
router.register(r'allattendance', AllAttendanceViewSet, base_name='allattendance')
router.register(r'audio', AudioRequestViewSet)
router.register(r'charts', ChartViewSet)
router.register(r'seats', SeatViewSet)
router.register(r'partials', PartialViewSet)
router.register(r'terms', TermViewSet)
router.register(r'classnotes', ClassNoteViewSet)
router.register(r'update-workers', UpdateWorkersViewSet, base_name='updateworkers')
router.register(r'update-workloads', ServiceSlotWorkloadViewSet, base_name='updateworkload')
router.register(r'update-active-services', ServiceActiveViewSet, base_name='updateservice')
router.register(r'update-time-services', ServiceTimeViewSet, base_name='updatetime')
router.register(r'update-exception-active', ExceptionActiveViewSet)
router.register(r'service-assignments', AssignmentViewSet, base_name='serviceassignments')
router.register(r'service-assignments-pin', AssignmentPinViewSet)
router.register(r'tables', TableViewSet)

attendance_router = routers.NestedSimpleRouter(router, r'attendance', lookup='attendance')
attendance_router.register(r'rolls', RollViewSet, base_name='rolls')
rolls_router = routers.NestedSimpleRouter(attendance_router, r'rolls', lookup='rolls')
attendance_router.register(r'events', EventViewSet, base_name='events')
events_router = routers.NestedSimpleRouter(attendance_router, r'events', lookup='events')
attendance_router.register(r'schedules', ScheduleViewSet, base_name='schedules')
schedules_router = routers.NestedSimpleRouter(attendance_router, r'schedules', lookup='schedules')
attendance_router.register(r'individualslips', IndividualSlipViewSet, base_name='individualslips')
leaveslips_router = routers.NestedSimpleRouter(attendance_router, r'individualslips', lookup='individualslips')
attendance_router.register(r'groupslips', GroupSlipViewSet, base_name='groupslips')
groupleaveslips_router = routers.NestedSimpleRouter(attendance_router, r'groupslips', lookup='groupslips')

urlpatterns += [
  url(r'^api/trainees/gender/(?P<gender>[BS])/$', TraineesByGender.as_view()),
  url(r'^api/trainees/term/(?P<term>[1234])/$', TraineesByTerm.as_view()),
  url(r'^api/trainees/team/(?P<pk>\d+)/$', TraineesByTeam.as_view()),
  url(r'^api/trainees/teamtype/(?P<type>\w+)/$', TraineesByTeamType.as_view()),
  url(r'^api/trainees/house/(?P<pk>\d+)/$', TraineesByHouse.as_view()),
  url(r'^api/trainees/locality/(?P<pk>\d+)/$', TraineesByLocality.as_view()),
  url(r'^api/trainees/hc/$', TraineesHouseCoordinators.as_view()),
  url(r'^api/', include(router.urls, namespace='rest_framework')),
  url(r'^api/', include(attendance_router.urls)),
  # third party
  url(r'^docs/', get_swagger_view(title='DJAttendance API documentation')),
  url(r'^explorer/', include('explorer.urls')),
  url(r'^select2/', include('django_select2.urls')),
]

urlpatterns += staticfiles_urlpatterns()
if settings.DEBUG:
  import debug_toolbar
  urlpatterns += [
    url(r'^__debug__/', include(debug_toolbar.urls)),
  ]

urlpatterns += [
  url(r'^notifications/', get_nyt_pattern()),
  url(r'wiki', get_wiki_pattern())
]

handler404 = 'ap.views.custom404errorview'  # if settings.DEBUG = FALSE
handler500 = 'ap.views.custom500errorview'  # if settings.DEBUG = FALSE
handler503 = 'ap.views.custom503errorview'  # if settings.DEBUG = FALSE

ap/attendance/urls.py
from django.conf.urls import url

from attendance import views
urlpatterns = [
  url(r'^submit/$', views.AttendancePersonal.as_view(), name='attendance-submit'),
  url(r'^rolls/$', views.RollsView.as_view(), name='class-rolls'),
  url(r'^rolls/class/$', views.ClassRollsView.as_view(), name='class-table-rolls'),
  url(r'^rolls/meal/$', views.MealRollsView.as_view(), name='meal-rolls'),
  url(r'^rolls/study/$', views.StudyRollsView.as_view(), name='study-rolls'),
  url(r'^rolls/house/$', views.HouseRollsView.as_view(), name='house-rolls'),
  url(r'^rolls/team/$', views.TeamRollsView.as_view(), name='team-rolls'),
  url(r'^rolls/ypc/$', views.YPCRollsView.as_view(), name='ypc-rolls'),
  url(r'^rolls/rfid/$', views.RFIDRollsView.as_view(), name='rfid-rolls'),
  url(r'^api/rolls/finalize/$', views.finalize, name='finalize'),
  url(r'^api/rolls/rfid/(?P<trainee_id>\d+)$', views.rfid_signin),
  url(r'^api/rolls/rfid-finalize/(?P<event_id>\d+)/(?P<event_date>\d{4}-\d{2}-\d{2})$', views.rfid_finalize, name='rfid-roll-finalize'),
  url(r'^api/rolls/rfid-tardy/(?P<event_id>\d+)/(?P<event_date>\d{4}-\d{2}-\d{2})$', views.rfid_tardy, name='rfid-roll-tardy'),
  url(r'^rolls/audit/$', views.AuditRollsView.as_view(), name='audit-rolls'),
  url(r'^admin/rolls/create/$', views.RollAdminCreate.as_view(), name='admin-roll-create'),
  url(r'^admin/rolls/(?P<pk>\d+)$', views.RollAdminUpdate.as_view(), name='admin-roll'),
  url(r'^admin/rolls/delete/(?P<pk>\d+)$', views.RollAdminDelete.as_view(), name='admin-roll-delete'),
  url(r'^admin/trainee-attendance/$', views.TraineeAttendanceAdminView.as_view(), name='admin-trainee-attendance'),
]

ap/attendance/models.py
from datetime import date, datetime

from accounts.models import Trainee, User
from django.core.urlresolvers import reverse
from django.db import models
from schedules.models import Event


""" attendance models.py
The attendance module takes care of data and logic directly related
to tracking attendance. It does not handle things such as schedules
or leave slips.

DATA MODELS:
  - Roll: an attendance record per trainee, per event.
      for example, if 10 trainees are supposed to be at an event,
      then there will be 10 roll objects associated to that event,
      as well as each trainee.
"""


class Roll(models.Model):

  ROLL_STATUS = (
      ('P', 'Present'),
      ('A', 'Absent'),
      ('T', 'Tardy'),
      ('U', 'Uniform'),
      ('L', 'Left Class')
  )

  event = models.ForeignKey(Event, null=True, on_delete=models.SET_NULL)

  trainee = models.ForeignKey(Trainee, null=True, related_name='rolls', on_delete=models.SET_NULL)

  status = models.CharField(max_length=1, choices=ROLL_STATUS)

  # once a roll is finalized, it can no longer be edited
  # except by a TA, attendance monitor, or other admin
  finalized = models.BooleanField(default=False)

  notes = models.CharField(max_length=200, blank=True)

  # the one who submitted this roll
  # for first year should be an attendance monitor, house coordinator, team monitor, or YPC monitor
  # for second year it can either by a second year trainee and/or any of the roles listed above
  # for second year there can be two roll objects per event, one submitted by the second year trainee and one submitted by a monitor, this is for audits

  submitted_by = models.ForeignKey(User, null=True, related_name='submitted_rolls', on_delete=models.SET_NULL)

  # when the roll was last updated
  last_modified = models.DateTimeField(auto_now=True)

  # the date of the event that corresponds with the roll.
  date = models.DateField()

  def __unicode__(self):
    try:
      # return status, trainee name, and event
      return "ID %s [%s] %s @ [%s] %s" % (self.id, self.date, self.event, self.status, self.trainee)
    except AttributeError as e:
      return str(self.id) + ": " + str(e)

  class Meta:
    ordering = ['-last_modified']
    unique_together = ('trainee', 'event', 'date', 'submitted_by')

  @staticmethod
  def update_or_create(validated_data):
    '''
      Creates roll if not existing, else update
      Reteurn None if event doesn't exist for roll
    '''

    event = validated_data['event']
    roll_date = validated_data['date']
    if type(roll_date) != type(date.today()):
      roll_date = datetime.strptime(roll_date, '%Y-%m-%d').date()
    submitted_by = validated_data['submitted_by']

    # checks if event exists for given event and date
    if not Event.objects.filter(name=event.name, weekday=roll_date.weekday()).exists():
      return None

    newroll, created = Roll.objects.update_or_create(**validated_data)

    return newroll

  def self_submitted(self):
    return self.trainee == self.submitted_by

  def get_absolute_url(self):
    return reverse('attendance:admin-roll', kwargs={'pk': self.id})

  def get_delete_url(self):
    return reverse('attendance:admin-roll-delete', kwargs={'pk': self.id})

ap/attendance/forms.py
from accounts.models import Trainee
from aputils.widgets import DatePicker
from attendance.models import Roll
from django import forms
from django.db.models import Max
from schedules.models import Event


class RollAdminForm(forms.ModelForm):

  def __init__(self, *args, **kwargs):
    trainee = None
    if 'trainee' in kwargs:
      trainee = kwargs.pop('trainee')
    super(RollAdminForm, self).__init__(*args, **kwargs)

    if trainee is not None:
      event_qs = Event.objects.none()
      for s in trainee.schedules.all():
        event_qs = event_qs | s.events.all()
      self.fields['event'].queryset = event_qs

    self.fields['event'].widget.attrs['class'] = 'select-fk'
    self.fields['trainee'].widget.attrs['class'] = 'select-fk'
    self.fields['submitted_by'].widget.attrs['class'] = 'select-fk'
    self.fields['date'].widget = DatePicker()

  def clean(self):
    cleaned_data = self.cleaned_data
    data_date = cleaned_data['date']
    data_event = cleaned_data['event']
    data_trainee = cleaned_data['trainee']
    data_submitted_by = cleaned_data['submitted_by']
    AMS = Trainee.objects.filter(groups__name='attendance_monitors')

    # Date needs to match the event weekday
    if not data_date.weekday() == data_event.weekday:  # 0 is Monday
      raise forms.ValidationError("Date selected does not match Event selected!!")

    # Roll date and event needs to match schedule week
    sched = data_event.schedules.filter(trainees__in=[data_trainee])
    pr = sched.aggregate(Max('priority'))['priority__max']
    if not sched.get(priority=pr).active_in_week(data_event.week_from_date(data_date)):
      raise forms.ValidationError("Event is not active for date selected!!")

    if data_trainee.self_attendance:
      if data_submitted_by.id != data_trainee.id and data_submitted_by not in AMS:
        raise forms.ValidationError("This is an invalid submitted_by!!")

    return cleaned_data

  class Meta:
    model = Roll
    fields = "__all__"

ap/attendance/templates/attendance/_attendance_data.html
<script>
  var Events = {{ events_bb|safe }};
  var GroupEvents = {{ groupevents_bb|safe }};
  var Rolls = {{ rolls_bb|safe}};
  var IndividualSlips = {{ individualslips_bb|safe }};
  var GroupSlips = {{ groupslips_bb|safe }};
  var Trainee = {{ trainee_bb|safe }};
  var Trainees = {{ trainees_bb|safe }};
  var TAs = {{ TAs_bb|safe }};
  var Term = {{ term_bb|safe }};
  var AM_GROUPS = {{ am_groups|safe }};
  {% if show %}
    var Show = '{{show}}';
  {% endif %}
  {% if disablePeriodSelect %}
    var DisablePeriodSelect = {{ disablePeriodSelect }};
  {% endif %}
  {% if Today %}
    var Today = moment('{{Today}}', 'MM/DD/YYYY');
  {% endif %}
  {% if SelectedEvents %}
    var SelectedEvents = {{ SelectedEvents|safe }};
  {% endif %}
  {% if actual_user %}
    var User = {{ actual_user | safe }};
  {% else %}
    var User = null;
  {% endif %}
</script>

ap/attendance/templates/attendance/roll_audit.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
  {{title}}
{% endblock %}

{% block scripts %}
{{ block.super }}
<script type="text/javascript">

var gen = "{{ user_gender.gender }}";
var table;

$(document).ready(function() {

  setdatatable();

  $( "body" ).on('click', '#generate_table', function(){
    generate();
  });

  $("body").on('click', 'span.glyphicon',function(){
    var state_tobe;

    if ($(this).attr('class') == 'glyphicon glyphicon-ok-circle'){
      $(this).attr('class', 'glyphicon glyphicon-remove-circle')
      $(this).attr('style', 'color:red')
      state_tobe = false
    }else if($(this).attr('class') == 'glyphicon glyphicon-remove-circle'){
      $(this).attr('class', 'glyphicon glyphicon-ok-circle')
      $(this).attr('style', 'color:green')
      state_tobe = true
    }

    var val = $(this).parent().attr('id');

    $.ajax({
      type: "POST",
      url: "{%url 'attendance:audit-rolls' %}",
      data: {id: val,
        state: state_tobe,
        csrfmiddlewaretoken: '{{ csrf_token }}'},
        success: function(response){
          new Notification(Notification.SUCCESS, 'Saved').show();
        },
      })
  });

  $("body").on('click', 'button.btn-secondary',function(){

    // replace content within modalBody to visualize the conflicts
    // $("#modalBody").html()
    // $(this).parent().parent().find("")
    console.log($(this).attr('id'))
    console.log("{{audit_log}}")

    $('#myModal').modal('toggle');
  })

});

function setdatatable(){
  table = $("#audittable").DataTable({
    info: true,
    autowidth: true,
    ordering: true,
    paging: false,
    order: []
  });
}

function generate(){
  var per = []
  $("#period button[aria-pressed=true]").each(function(){
    per.push($(this).text());
  })

  var gen = ""
  if ($("#gender button[aria-pressed=true]").length == 2){
    gen = "both"
  } else if ($("#gender button[aria-pressed=true]").length == 1){
    gen = $("#gender button[aria-pressed=true]").text()
  }

  $.ajax({
    type: "GET",
    url: "{%url 'attendance:audit-rolls' %}",
    data: {gender: gen,
      period: per,
      csrfmiddlewaretoken: '{{ csrf_token }}',
      ask: 'respond'},
      success: function (response){
        mytag = $('<div></div>').html(response);
        tbod = $('table',mytag).filter("#audittable")[0]
        $("#audittable").html(tbod.children);
        table.destroy();
        setdatatable();
      },
    })

}

</script>
{% endblock %}

{% block references %}
{{ block.super }}
<!-- Disable scaling to remove click delay on mobile for this page -->
<meta name="viewport" content="width=device-width, user-scalable=no">
<style type="text/css">

#gender{display:inline-block;margin-right:10px; margin-top: 10px; margin-bottom: 10px}
#period{display:inline-block;margin-right:10px;}
#generate_table{display:inline-block;}

</style>
{% endblock %}

{% block content %}

<h2>Audit Second Year Trainees</h2>

<br>

<div id="gender">
  Show:
  <div class="btn-group" role="group">
    <button class="btn btn-primary" data-toggle="button" id="bro">brothers</button>
    <button class="btn btn-primary" data-toggle="button" id="sis">sisters</button>
  </div>
</div>
<div id="period">
  Periods:
  <div class="btn-group" role="group">
    {% for i in "0123456789" %}
    <button class="btn btn-primary" data-toggle="button" id="per{{ i }}" {% if forloop.counter0 > current_period %}disabled{% endif %}>{{ i }}</button>
    {% endfor %}
  </div>
</div>
<button class="btn btn-primary" id="generate_table">Generate</button>

<table id="audittable" class="display" cellspacing="0" style="table-layout: fixed; width: 100%">
  <thead>
    <tr>
      <th>Under Audit</th>
      <th>Trainees</th>
      <th>Mismatched Frequencies</th>
      <th>A/T Discrepancy</th>
      <!-- <th>Rolls Detail - visualize</th> -->
      <th>Rolls Detail - Text</th>
    </tr>
  </thead>
  <tbody id="tablebody">
    {% for a in audit_log %}
    <tr>
      <td id="audit_stat{{a.2.id}}">{% if a.1 == True %}
        <span class="glyphicon glyphicon-ok-circle" style="color:green"></span>
        {% elif a.1 == False %}
        <span class="glyphicon glyphicon-remove-circle" style="color:red"></span>
        {% endif %}
        <div hidden>{{a.1}}</div>
      </td>
      <td>{{a.2.lastname}}, {{a.2.firstname}}</td>
      <td>{{a.3}}</td>
      <td>{{a.4}}</td>
<!--       <td>
        {% if a.3 > 0 or a.4 > 0 %}
          <button class="btn btn-secondary" id="modal{{a.2.id}}">Visual Display</button>
        {% endif %}
      </td> -->
      <td>
      {{a.5}}
    </td>
  </tr>
  {% endfor %}
</tbody>
</table>

{% endblock %}
{% block post_container %}

<!-- modal to display visual discrepency -->
<!-- <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Title Placement</h4>
      </div>
      <div class="modal-body" id="modalBody">
        Modal Body Placement
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div> -->



{% endblock %}

ap/attendance/templates/attendance/roll_table_admin.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load common_tags %}

{% block scripts %}
{{ block.super }}
{% endblock %}

{% block references %}
{{ block.super }}
{% endblock %}


{% block title %}
{{title}}
{% endblock %}

{% block content %}

{% ifusergroup attendance_monitors|training_assistant %}
<ul class="nav nav-tabs" role="tablist">
  <li role="presentation" {% if event_type == 'C' %} class="active" {% endif %}><a href="{% url 'attendance:class-table-rolls'%}" role="tab">Class</a></li>
  <li role="presentation" {% if event_type == 'M' %} class="active" {% endif %}><a href="{% url 'attendance:meal-rolls'%}" role="tab">Meal</a></li>
  <li role="presentation" {% if event_type == 'S' %} class="active" {% endif %}><a href="{% url 'attendance:study-rolls'%}" role="tab">Study</a></li>
  <li role="presentation" {% if event_type == 'H' %} class="active" {% endif %}><a href="{% url 'attendance:house-rolls'%}" role="tab">House</a></li>
  <li role="presentation" {% if event_type == 'T' %} class="active" {% endif %}><a href="{% url 'attendance:team-rolls'%}" role="tab">Team</a></li>
  <li role="presentation" {% if event_type == 'Y' %} class="active" {% endif %}><a href="{% url 'attendance:ypc-rolls'%}" role="tab">YPC</a></li>
</ul>
{% endifusergroup %}

{% include "attendance/roll_table.html" %}

{% endblock %}

ap/attendance/templates/attendance/trainee_attendance_admin_view.html
{% extends "base.html" %}
{% load staticfiles %}
{% load bootstrap3 %}
{% load common_tags %}

{% block title %}{{ page_title }}{% endblock %}

{% block scripts %}

<script type="text/javascript">
  $(document).ready(() => {
    $("#id_trainee").select2()
      .on("select2:select", (e) => {
        $('form').submit();
      });

    $("table").DataTable({
      autoWidth: true,
      dom: '<"row"<"col-sm-6"Bl><"col-sm-6"f>>' +
      '<"row"<"col-sm-12"<"table-responsive"tr>>>' +
      '<"row"<"col-sm-5"i><"col-sm-7"p>>',

    });
  });
</script>
{% endblock %}

{% block content %}

<h1>{{page_title}}</h1>
<form action='' method='get'>
  <select id="id_trainee" name="trainee_id">
    {% for tr in trainee_list %}
      <option value="{{tr.id}}">{{tr.firstname}} {{tr.lastname}}</option>
    {% endfor %}
  </select>
</form>
<h2>{{trainee}}</h2>
<h3>Schedules</h3>
<div class="data-table-container">
  <table id="id_schedules_table" class="table table-striped table-bordered">
    <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Comments</th>
      </tr>
    </thead>
    <tbody>
      {% for schedule in schedules %}
        <tr>
          <td>{{schedule.id}}</td>
          <td>{{schedule}}</td>
          <td>{{schedule.comments}}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

<h3>Events</h3>
<div class="data-table-container">
  <table id="id_events_table" class="table table-striped table-bordered">
    <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
      </tr>
    </thead>
    <tbody>
      {% for event in events %}
        <tr>
          <td>{{event.id}}</td>
          <td>{{event}}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

<h3>Rolls</h3>
<div class="data-table-container">
  <table id="id_rolls_table" class="table table-striped table-bordered">
    <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
      </tr>
    </thead>
    <tbody>
      {% for roll in rolls %}
        <tr>
          <td>{{roll.id}}</td>
          <td>{{roll}}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}