ap/ap/urls.py
# coding: utf-8
import django
from django.conf import settings
from django.conf.urls import include, url
from django.contrib.auth.views import login as auth_login, logout_then_login
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from .views import home, custom404errorview, custom500errorview, custom503errorview
from accounts.views import *
from audio.views import AudioRequestViewSet
from schedules.views import EventViewSet, ScheduleViewSet, AllEventViewSet, AllScheduleViewSet
from attendance.views import RollViewSet, AllRollViewSet, AttendanceViewSet, AllAttendanceViewSet
from leaveslips.views import IndividualSlipViewSet, GroupSlipViewSet, AllIndividualSlipViewSet, AllGroupSlipViewSet
from books.views import BooksViewSet
from lifestudies.views import DisciplineSummariesViewSet
from seating.views import ChartViewSet, SeatViewSet, PartialViewSet
from terms.views import TermViewSet
from services.views import UpdateWorkersViewSet, ServiceSlotWorkloadViewSet, ServiceActiveViewSet, AssignmentViewSet, AssignmentPinViewSet, ServiceTimeViewSet, ExceptionActiveViewSet
from meal_seating.views import TableViewSet
from web_access.forms import WebAccessRequestGuestCreateForm as form
from classnotes.views import ClassNoteViewSet

from rest_framework_swagger.views import get_swagger_view
from rest_framework_nested import routers
from rest_framework_bulk.routes import BulkRouter

from wiki.urls import get_pattern as get_wiki_pattern
from django_nyt.urls import get_pattern as get_nyt_pattern

admin.autodiscover()

urlpatterns = [
  url(r'^$', home, name='home'),
  url(r'^accounts/login/$', auth_login, {'extra_context': {'webaccess_form': form}}, name='login'),
  url(r'^accounts/logout/$', logout_then_login, name='logout'),
  url(r'^accounts/', include('accounts.urls')),
  url(r'^audio/', include('audio.urls', namespace='audio')),
  url(r'^dailybread/', include('dailybread.urls', namespace="dailybread")),
  url(r'^badges/', include('badges.urls', namespace="badges")),
  url(r'^schedules/', include('schedules.urls', namespace="schedules")),
  url(r'^attendance/', include('attendance.urls', namespace="attendance")),
  url(r'^leaveslips/', include('leaveslips.urls', namespace="leaveslips")),
  url(r'^verse_parse/', include('verse_parse.urls', namespace="verse_parse")),
  url(r'^meal_seating/', include('meal_seating.urls')),
  url(r'^absent_trainee_roster/', include('absent_trainee_roster.urls', namespace="absent_trainee_roster")),
  url(r'^syllabus/', include('syllabus.urls', namespace="syllabus")),
  url(r'^classnotes/', include('classnotes.urls', namespace="classnotes")),
  url(r'^classes/', include('classes.urls', namespace="classes")),
  url(r'^lifestudies/', include('lifestudies.urls', namespace="lifestudies")),
  url(r'^seating/', include('seating.urls', namespace='seating')),
  url(r'^exams/', include('exams.urls', namespace="exams")),
  url(r'^web_access/', include('web_access.urls', namespace="web_access")),
  url(r'^apimport/', include('apimport.urls', namespace="apimport")),
  url(r'^bible_tracker/', include('bible_tracker.urls', namespace='bible_tracker')),
  url(r'^announcements/', include('announcements.urls', namespace='announcements')),
  url(r'^services/', include('services.urls', namespace="services")),
  url(r'^semi/', include('semi.urls', namespace="semi")),
  url(r'^house_requests/', include('house_requests.urls', namespace="house_requests")),
  url(r'^hc/', include('hc.urls', namespace="hc")),
  url(r'^room_reservations/', include('room_reservations.urls', namespace="room_reservations")),
  url(r'^graduation/', include('graduation.urls', namespace="graduation")),
  url(r'^xb/', include('xb_application.urls', namespace="xb")),
  url(r'^interim/', include('interim.urls', namespace="interim")),
  # admin urls
  url(r'^adminactions/', include('adminactions.urls')),  # django-adminactions pluggable app
  url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
  url(r'^admin/', include(admin.site.urls)),
  url(r'^admin/', include("massadmin.urls")),
  url(r'^static/(?P<path>.*)$', django.views.static.serve, {'document_root': settings.STATIC_ROOT}),
  # fobi urls
  # DB Store plugin URLs
  url(r'^fobi/plugins/form-handlers/db-store/', include('fobi.contrib.plugins.form_handlers.db_store.urls')),
  url(r'^fobi/plugins/form-wizard-handlers/db-store/', include('fobi.contrib.plugins.form_handlers.db_store.urls.form_wizard_handlers')),
  # View URLs
  url(r'^forms/', include('fobi.urls.view')),
  # Edit URLs
  url(r'^forms/', include('fobi.urls.edit')),
  url(r'^404/$', custom404errorview),  # for development
  url(r'^500/$', custom500errorview),  # for development
  url(r'^503/$', custom503errorview),  # for development
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

router = BulkRouter()
router.register(r'users', UserViewSet)
router.register(r'trainees', TraineeViewSet, base_name='trainees')
router.register(r'events', EventViewSet)
router.register(r'allevents', AllEventViewSet, base_name='allevents')
router.register(r'schedules', ScheduleViewSet)
router.register(r'allschedules', AllScheduleViewSet, base_name='allschedules')
router.register(r'rolls', RollViewSet)
router.register(r'allrolls', AllRollViewSet, base_name='allrolls')
router.register(r'individualslips', IndividualSlipViewSet)
router.register(r'allindividualleaveslips', AllIndividualSlipViewSet, base_name='allindividualslips')
router.register(r'groupslips', GroupSlipViewSet)
router.register(r'allgroupslips', AllGroupSlipViewSet, base_name='allgroupslips')
router.register(r'books', BooksViewSet)
router.register(r'summaries', DisciplineSummariesViewSet)
router.register(r'attendance', AttendanceViewSet)
router.register(r'allattendance', AllAttendanceViewSet, base_name='allattendance')
router.register(r'audio', AudioRequestViewSet)
router.register(r'charts', ChartViewSet)
router.register(r'seats', SeatViewSet)
router.register(r'partials', PartialViewSet)
router.register(r'terms', TermViewSet)
router.register(r'classnotes', ClassNoteViewSet)
router.register(r'update-workers', UpdateWorkersViewSet, base_name='updateworkers')
router.register(r'update-workloads', ServiceSlotWorkloadViewSet, base_name='updateworkload')
router.register(r'update-active-services', ServiceActiveViewSet, base_name='updateservice')
router.register(r'update-time-services', ServiceTimeViewSet, base_name='updatetime')
router.register(r'update-exception-active', ExceptionActiveViewSet)
router.register(r'service-assignments', AssignmentViewSet, base_name='serviceassignments')
router.register(r'service-assignments-pin', AssignmentPinViewSet)
router.register(r'tables', TableViewSet)

attendance_router = routers.NestedSimpleRouter(router, r'attendance', lookup='attendance')
attendance_router.register(r'rolls', RollViewSet, base_name='rolls')
rolls_router = routers.NestedSimpleRouter(attendance_router, r'rolls', lookup='rolls')
attendance_router.register(r'events', EventViewSet, base_name='events')
events_router = routers.NestedSimpleRouter(attendance_router, r'events', lookup='events')
attendance_router.register(r'schedules', ScheduleViewSet, base_name='schedules')
schedules_router = routers.NestedSimpleRouter(attendance_router, r'schedules', lookup='schedules')
attendance_router.register(r'individualslips', IndividualSlipViewSet, base_name='individualslips')
leaveslips_router = routers.NestedSimpleRouter(attendance_router, r'individualslips', lookup='individualslips')
attendance_router.register(r'groupslips', GroupSlipViewSet, base_name='groupslips')
groupleaveslips_router = routers.NestedSimpleRouter(attendance_router, r'groupslips', lookup='groupslips')

urlpatterns += [
  url(r'^api/trainees/gender/(?P<gender>[BS])/$', TraineesByGender.as_view()),
  url(r'^api/trainees/term/(?P<term>[1234])/$', TraineesByTerm.as_view()),
  url(r'^api/trainees/team/(?P<pk>\d+)/$', TraineesByTeam.as_view()),
  url(r'^api/trainees/teamtype/(?P<type>\w+)/$', TraineesByTeamType.as_view()),
  url(r'^api/trainees/house/(?P<pk>\d+)/$', TraineesByHouse.as_view()),
  url(r'^api/trainees/locality/(?P<pk>\d+)/$', TraineesByLocality.as_view()),
  url(r'^api/trainees/hc/$', TraineesHouseCoordinators.as_view()),
  url(r'^api/', include(router.urls, namespace='rest_framework')),
  url(r'^api/', include(attendance_router.urls)),
  # third party
  url(r'^docs/', get_swagger_view(title='DJAttendance API documentation')),
  url(r'^explorer/', include('explorer.urls')),
  url(r'^select2/', include('django_select2.urls')),
]

urlpatterns += staticfiles_urlpatterns()
if settings.DEBUG:
  import debug_toolbar
  urlpatterns += [
    url(r'^__debug__/', include(debug_toolbar.urls)),
  ]

urlpatterns += [
  url(r'^notifications/', get_nyt_pattern()),
  url(r'wiki', get_wiki_pattern())
]

handler404 = 'ap.views.custom404errorview'  # if settings.DEBUG = FALSE
handler500 = 'ap.views.custom500errorview'  # if settings.DEBUG = FALSE
handler503 = 'ap.views.custom503errorview'  # if settings.DEBUG = FALSE

ap/syllabus/urls.py
from django.conf.urls import url
from syllabus.views import CLView, SyllabusDetailView, HomeView, DetailView, TestView, DeleteSyllabusView, AddSyllabusView, AddSessionView, DeleteSessionView
from terms.models import Term

urlpatterns = [

  url(r'^$', HomeView.as_view(model=Term), name='home-view'),

  url(r'^(?P<term>(Fa|Sp)\d{2})/$', CLView.as_view(), name='classlist-view'),

  url(r'^(?P<term>(Fa|Sp)\d{2})/(?P<kode>\D{0,5})/(?P<pk>\d+)$',
    DetailView.as_view(), name='detail-view'),

  url(r'^(?P<term>(Fa|Sp)\d{2})/add_syllabus$',
    AddSyllabusView.as_view(), name='add-syllabus'),

  url(r'^(?P<term>(Fa|Sp)\d{2})/delete/(?P<pk>\d+)$',
    DeleteSyllabusView.as_view(), name='delete-syllabus'),

  url(r'^(?P<term>(Fa|Sp)\d{2})/(?P<kode>\D{0,5})/add_session/(?P<pk>\d+)$',
    AddSessionView.as_view(), name='add-session'),

  url(r'^(?P<term>(Fa|Sp)\d{2})/(?P<kode>\D{0,5})/(?P<syllabus_pk>\d+)/delete_session/(?P<pk>\d+)$',
    DeleteSessionView.as_view(), name='delete-session'),

  # url(r'^Term/(?P<kode>\D+)/$', DetailView.as_view(model=Syllabus), name='detail-view'),

]

ap/syllabus/models.py
from django.db import models
from classes.models import Class
from books.models import Book

from time import strftime

from django.contrib.postgres.fields import ArrayField

from django.core.urlresolvers import reverse, reverse_lazy

""" SYLLABUS models.py

This module catalogs all pertinent data associated with classes in the FTTA
for use in in other functions. For example, Data includes class name, date,
assignments, books, midterms, etc. Inputted data is organized into a
readable form for the entire term.

Data Models:
  - Syllabus:
    class_syllabus (ForeignKey: Class)
  - ClassSession:
    date
    topic
    book (ForeignKey: Book) - name(?), code
    assignment[]
    note
    exam (boolean, HIDDEN)
    syllabus (ForeignKey: Syllabus)
"""

class Syllabus (models.Model):

  # which class this syllabus belongs to
  class_syllabus = models.ForeignKey(Class, on_delete=models.SET_NULL, null=True)

  # whether assignment is read before or after class (== true)
  after = models.BooleanField(default=False)

  # def get_absolute_url(self):
  #   return reverse('self.class_syllabus.code')

  def get_absolute_url(self):
    return '%s/' % self.class_syllabus.term.code #reverse_lazy('detail-view', kwargs={'after': self.class_syllabus.code})

  def get_url(self):
    return '%s/' % self.class_syllabus.code

  def get_id(self):
    slug = self.id
    return slug

  class Meta:
    verbose_name_plural = 'syllabi'

  # @property
  # def _get_code(self):
  #   code= self.class_syllabus.code
  #   return code

  # codes = property(_get_code)

  def __unicode__(self):
    try:
      return (self.class_syllabus.name + " | " + self.class_syllabus.term.name)
    except AttributeError as e:
      return str(self.id) + ": " + str(e)

  # code = Syllabus.class_syllabus.code

  # def get_code(self):
  #   code = self.class_syllabus.term.name
  #   return code


class ClassSession(models.Model):

  # date of the class
  date = models.DateField(verbose_name='session date')

  # topic; "exam";
  topic = models.CharField(max_length=200)

  # book name, code
  """ TO DO: Make this OPTIONAL. """
  """and make this multiple"""
  book = models.ForeignKey(Book, on_delete=models.SET_NULL, null=True)

  # assignment info (pages; chapters; msgs; lessons; verses; exam: "FINAL, MIDTERM, ETC")
    # can list multiple assigments, e.g. memory verses
  assignment = ArrayField(models.CharField(max_length=100, blank=True), default=list())

  # exam (HIDDEN)
  exam = models.BooleanField(default=False)

  # the class syllabus this session refers to
  syllabus = models.ForeignKey(Syllabus, on_delete=models.SET_NULL, null=True)

  def __unicode__(self):
    try:
      return (self.syllabus.class_syllabus.name + " | "
          + self.syllabus.class_syllabus.term.name + " | " +
          self.date.strftime('%Y/%m/%d') + " | " + self.topic)
    except AttributeError as e:
      return str(self.id) + ": " + str(e)

ap/syllabus/forms.py
from django import forms
from .models import Syllabus, ClassSession

class NewSyllabusForm(forms.ModelForm):

  class Meta:
    model = Syllabus
    fields = '__all__'
    #widgets = {
    #  'start': DatepickerWidget(),
    #  'end': DatepickerWidget()
    #}

  def save(self, commit=True):
    #data = self.cleaned_data
    syllabus = super(NewSyllabusForm, self).save(commit=False)
    #syllabus.season = data['season']
    #syllabus.name = data['season']
    #syllabus.code = syllabus.name[:2]
    #syllabus.start = data['start']
    #syllabus.end = data['end']

    #if syllabus.start.year == syllabus.end.year:
    #  syllabus.name += ' ' + str(syllabus.start.year)
    #  syllabus.code += str(syllabus.start.year)[2:]
##    else:
      # error
    ## check if term code has duplicate??

    if commit:
      syllabus.save()
    return syllabus

class NewSessionForm(forms.ModelForm):

  class Meta:
    model = ClassSession
    fields = '__all__'

  def save(self, commit=True):
    session = super(NewSessionForm, self).save(commit=False)
    if commit:
      session.save()
    return session

ap/syllabus/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import ListView, TemplateView, DetailView, ArchiveIndexView, CreateView, DeleteView
from django.template import RequestContext
from django.core.urlresolvers import reverse_lazy

from terms.models import Term

from .forms import NewSyllabusForm
from .models import Syllabus, ClassSession

class HomeView(ListView):
  template_name = "syllabus/termlist.html"
  model = Term
  context_object_name = 'termlist'

class CLView(ListView):
  template_name = "syllabus/classlist.html"
  context_object_name = 'list'
  model = Syllabus

  """this is to get ?P<term> from urls.py
  and make it accessible to the template classlist.html
  by using {{term}}"""
  def get_context_data(self, **kwargs):
    context = super(CLView, self).get_context_data(**kwargs)
    term = self.kwargs['term']
    context['term'] = term
    context['term_id'] = filter(lambda t: t.code == term, Term.objects.all())[0].id
    return context
  # def get_queryset(self):
  #   term = self.kwargs['term']

class DetailView(DetailView):
  template_name = "syllabus/details.html"
  model = Syllabus
  context_object_name = 'syllabus'
  slug_url_kwarg = 'term','kode'

  def get_context_data(self, **kwargs):
    context = super(DetailView, self).get_context_data(**kwargs)
    context['term'] = self.kwargs['term']
    context['kode'] = self.kwargs['kode']
    context['pk'] = self.kwargs['pk']
    return context

  # def get_queryset(self):
  #   kode = self.kwargs['kode']
  #   term = self.kwargs['term']
  #   return Syllabus.objects.filter(class_syllabus__code= kode)
  #   # .filter(class_syllabus__term = term)

class AddSyllabusView(CreateView):
  model = Syllabus
  template_name = 'syllabus/new_syllabus_form.html'
  form_class = NewSyllabusForm

  def get_context_data(self, **kwargs):
    context = super(AddSyllabusView, self).get_context_data(**kwargs)
    context['term'] = self.kwargs['term']
    return context

  def get_success_url(self):
    term = self.kwargs['term']
    return reverse_lazy('syllabus:classlist-view', kwargs=self.kwargs)

class DeleteSyllabusView(DeleteView):
  model = Syllabus
  template_name = 'syllabus/delete_syllabus_confirm.html'
  # def get_queryset(self):
  #   term = self.kwargs['term']
  def get_success_url(self):
    term = self.kwargs['term']
    return reverse_lazy('syllabus:classlist-view', kwargs={'term': term})

class TestView(ListView):
  template_name = "syllabus/detail.html"
  model = Syllabus
  context_object_name = 'syl_list'

class SyllabusDetailView(ListView):
  model = Syllabus
  template_name = "syllabus/detail.html"
  context_object_name = 'syllabus'
  slug_field = 'code'
  slug_url_kwarg = 'code'

# class SLView(ListView):
#   model = Session
#   template_name = 'session/sessionlist.html'
#   context_object_name = 'ses_list'

class AddSessionView(CreateView):
  model = ClassSession
  template_name = 'session/new_session_form.html'

  def get_success_url(self):
    term = self.kwargs['term']
    kode = self.kwargs['kode']
    pk = self.kwargs['pk']
    return reverse_lazy('syllabus:detail-view', kwargs=self.kwargs)

class DeleteSessionView(DeleteView):
  model = ClassSession
  template_name = 'session/delete_session_confirm.html'
  # def get_queryset(self):
  #   term = self.kwargs['term']
  def get_success_url(self):
    term = self.kwargs['term']
    kode = self.kwargs['kode']
    syllabus_pk = self.kwargs['syllabus_pk']
    return reverse_lazy('syllabus:detail-view', args=[term,kode,syllabus_pk])

ap/syllabus/templates/syllabus/ClassSyllabus.html
<p> Hey world, this is detail.html for syllabus instead. </p>




<h1> Session List: </h1>

<p> session date: </p>
{% if sl %}

  <ul>
  {% for session in sl  %}

    {% if session.syllabus.class_syllabus %}
    <p> test </p>
     {% endif %}

  <li> <p> {{session.syllabus.class_syllabus}} </p> </li>



  {% endfor %}



  </br>
  </ul>



<p> session topic: </p>
  <ul>
  {% for session in sl %}
    <li> {{session.topic}}  </li>
  {% endfor %}
  </ul>

<p> session book: </p>
  <ul>
  {% for session in sl %}
    <li>  {{session.book}}  </li>
  {% endfor %}
  </ul>

<p> session name: </p>
  <ul>
  {% for session in sl %}
    <li> {{session.syllabus}} </li>
  {% endfor %}
  </ul>

{% else %}
  <p>No sessions.</p>
{% endif %}

ap/syllabus/templates/syllabus/classlist.html
{% extends "base.html" %}

{% block content %}
</br>

<a href="{% url 'syllabus:home-view' %}">Back to term list.</a>

<h1> Class List: </h1>

<!-- {% if list %}
  <ul>
  {% for syllabus in list %}
  <li> <a href="{{ syllabus.get_url_path }}" >{{ syllabus.class_syllabus }} </a> </li>
  {% endfor %}
  </ul>
{% else %}
  <p>No syllabus.</p>
{% endif %}


{% if list %}
  <ul>
  {% for syllabus in list %}
  <li> <a href="{{syllabus.get_id}}" > {{ syllabus.class_syllabus.code }} </a> </li>
  {% endfor %}
  </ul>
{% else %}
  <p>No syllabus.</p>
{% endif %} -->

{% if list %}
  <ul>
  {% for syllabus in list %}
  <table>
  <tr>
    <td><a href="{{syllabus.get_url}}{{syllabus.id}}" > {{ syllabus.class_syllabus.name }}: {{syllabus.class_syllabus.term.code }} </a> </td>
    <td><a href="delete/{{syllabus.id}}">Delete</a></td>
  </tr>
  </table>
  {% endfor %}
  </ul>
{% else %}
  <p>No syllabus.</p>
{% endif %}

<br>
<a href="{% url 'syllabus:add-syllabus' term=term %}"> {{syllabus.class_syllabus.term.code}} Add a Syllabus </a>
</br>
{% endblock %}

ap/syllabus/templates/syllabus/delete_syllabus_confirm.html
{% extends "base.html" %}

{% block content %}
{{ form.media }}

<h1>Delete syllabus</h1>

<form action="" method="post">
	{% csrf_token %}
	<input type="submit" value="Delete">
</form>
{% endblock %}

ap/syllabus/templates/syllabus/detail.html
// DEBUG:
<p> Hey world, this is detail.html for syllabus instead. </p>
<p>The current url path is {{ request.get_full_path }}</p>
<p># of Syllabii: {{ syl_list|length }}</p>

<h1> {{syl_list}} </h1>
---
<br><br>
<b>FULL-TIME TRAINING IN ANAHEIM</b>

{% if syl_list %}
  {% for syllabus in syl_list %}
  <!-- /////////////////
  TO DO:
    - (psuedocode):
      - if: the syllabus == the class.id in the URL
        - then: display the syllabus.
      - else: don't display the syllabus.
    - so:
      - how to track what class user selected
    -


   ///////////////////// -->
    <h2>
      <p>
      {{ syllabus.class_syllabus.term }} |
      {{ syllabus.class_syllabus.name }}
      </p>
    </h2>
      <p>Syllabus</p>

      {% if syllabus.after %}
        Complete the assigned reading AFTER each class section
      {% else %}
        Complete the assigned reading BEFORE each class section
      {% endif %}


      <h5>// (debug) # of Sessions: {{ syllabus.session_set.all|length }}</h5>
    </h4>
      {% if syllabus.session_set.all %}
        <h4>
        {% for session in syllabus.session_set.all %}
        <p>
            <!-- TO DO:
               add leading zero to session.date.month
            -->
            Date: {{ session.date.month }}/{{ session.date.day }} |
            {% if session.exam %}
              Topic: EXAM |
            {% else %}
              Topic: {{ session.topic }} |
            {% endif %}
            {% if session.exam %}
              {{ session.assignment }}
            {% else %}
            {% if session.book %}
              Reading Assignment: {{ session.book.code }},
            {% endif %}
              {{ session.assignment }}
            {% endif %}
        </p>
        {% endfor %}
        </h4>

        <p>
        {% for session in syllabus.session_set.all %}
          {{ session.book.code }} - {{ session.book }}<br>
        {% endfor %}
        </p>
      {% endif %}

    <!-- TO DO: get session related objects by doing a REVERSE relationship from SYLLABUS object. -->
  {% endfor %}

{% endif %}


---
<br><br>
// end of all syllabus

<br><br>

ap/syllabus/templates/syllabus/details.html
{% extends "base.html" %}

{% block content %}
<br>

<a href="{% url 'syllabus:home-view' %}"> Back to term list.</a>
<br>
<a href="{% url 'syllabus:classlist-view' term=term %}"> Back to syllabus list.</a>
<br>
<a href="{% url 'syllabus:add-session' term=term kode=kode pk=pk %}"> Add a session.</a>
<!--
{% if syllabus %}
	<ul>
		<li><a href="{{ syllabus.class_syllabus.code }}">{{ syllabus.class_syllabus }}</a></li>
		<li> <a href="{{ syllabus.get_url_path }}" >{{ syllabus.class_syllabus }} </a> </li>
		<p> {{syllabus.class_syllabus.code}} </p>
	</ul>
{% else %}
	<p>No syllabus.</p>
{% endif %}
-->

{% if kode == syllabus.class_syllabus.code %}
	<h1>{{ syllabus.class_syllabus }}</h1>
	<p>Course Code: {{ syllabus.class_syllabus.code }}</p>
	<p>Course Name: {{ syllabus.class_syllabus.name }}</p>
	<p>Course Term: {{ syllabus.class_syllabus.term }}</p>
	<p>When to Read:
	{% if syllabus.after %}
				Complete the assigned reading AFTER each class section
	{% else %}
				Complete the assigned reading BEFORE each class section
	{% endif %}
	</p>
{% endif %}

<p> {{session.date}} </p>

<!-- <h5>// (debug) # of Sessions: {{ syllabus.session_set.all|length }}</h5> -->

<!-- GET A REALLY WEIRD ERROR - CAN ONLY ACCESS SYLLABUS.class_syllabus.CODE IF ITS INSIDE A IF / FOR LOOP. DOESN'T WORK STAND ALONE?! -->
{% if syllabus.session_set.all %}
	<h4>
	{% for session in syllabus.session_set.all %}
	<li>
		Date: {{ session.date | date:"m" }}/{{ session.date | date:"d" }} |
		{% if session.exam %}
			Topic: EXAM |
		{% else %}
			Topic: {{ session.topic }} |
		{% endif %}
		{% if session.exam %}
			{% for x in session.assignment %}
				{{x}}
			{% endfor %}
		{% else %}
			{% if session.book %}
				Reading Assignment: {{ session.book.code }},
			{% endif %}
			{% for x in session.assignment %}
				{{x}}
			{% endfor %}
		{% endif %}
		<td><a href="{% url 'delete-session' term kode syllabus.id session.id%}">Delete</a></td>
	</li>
	{% endfor %}
	</h4>

	<p>
		<!--TO DO: make this display unique books-->
	{% for session in syllabus.session_set.all %}
		{{ session.book.code }} - {{ session.book }}<br>
	{% endfor %}
	</p>
{% endif %}
{% endblock %}

ap/syllabus/templates/syllabus/index.html
<!-- attempt to copy old attendance server syllabus index.php view -->

<!-- Current Selected term is: Currentterm variable

Pick term: Selector botton + Go button

Add a book

Name: input       Code: input         Cat 8:   input field

link to first year class assignments "class reading schedule"

link to second year class assingments "class reading schedule"

List of Individual Syllibi:

link to fmoc syllabus       Edit       New         Delete


 -->


This is an attempt to copy the old attendance server "Syllabus" index.php view

<p> Current Selected Term is: Term????  </p>

<p> Pick Term: </p> 

	<select>
	  <option value="Fa12">Fall 2012</option>
	  <option value="Sp13">Spring 2013</option>
	  <option value="Fa13">Fall 2013</option>
	  
	</select>

	<p> fall 2012 </p>

	<p> term.current term </p>

<!-- skip book input for now -->

ap/syllabus/templates/syllabus/new_syllabus_form.html
{% extends "base.html" %}

{% block references %}
  {{ form.media }}
{% endblock %}

{% block content %}
<a href="{% url 'syllabus:classlist-view' term=term %}">Back to syllabus list.</a>

<h1>Add new syllabus</h1>

{% if form.errors %}
	<p style="color: red;">
		Please correct the error{{ form.errors|pluralize }} below.
	</p>
{% endif %}

<form action="" method="post">
	<table>
		{{ form.as_table }}
	</table>
	{% csrf_token %}

	<input type="submit" value="Submit">
</form>
{% endblock %}

ap/syllabus/templates/syllabus/readingschedule.html
<p> This is a test for the reading schedule view </p>