ap/ap/urls.py
# coding: utf-8
import django
from django.conf import settings
from django.conf.urls import include, url
from django.contrib.auth.views import login as auth_login, logout_then_login
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from .views import home, custom404errorview, custom500errorview, custom503errorview
from accounts.views import *
from audio.views import AudioRequestViewSet
from schedules.views import EventViewSet, ScheduleViewSet, AllEventViewSet, AllScheduleViewSet
from attendance.views import RollViewSet, AllRollViewSet, AttendanceViewSet, AllAttendanceViewSet
from leaveslips.views import IndividualSlipViewSet, GroupSlipViewSet, AllIndividualSlipViewSet, AllGroupSlipViewSet
from books.views import BooksViewSet
from lifestudies.views import DisciplineSummariesViewSet
from seating.views import ChartViewSet, SeatViewSet, PartialViewSet
from terms.views import TermViewSet
from services.views import UpdateWorkersViewSet, ServiceSlotWorkloadViewSet, ServiceActiveViewSet, AssignmentViewSet, AssignmentPinViewSet, ServiceTimeViewSet, ExceptionActiveViewSet
from meal_seating.views import TableViewSet
from web_access.forms import WebAccessRequestGuestCreateForm as form
from classnotes.views import ClassNoteViewSet

from rest_framework_swagger.views import get_swagger_view
from rest_framework_nested import routers
from rest_framework_bulk.routes import BulkRouter

from wiki.urls import get_pattern as get_wiki_pattern
from django_nyt.urls import get_pattern as get_nyt_pattern

admin.autodiscover()

urlpatterns = [
  url(r'^$', home, name='home'),
  url(r'^accounts/login/$', auth_login, {'extra_context': {'webaccess_form': form}}, name='login'),
  url(r'^accounts/logout/$', logout_then_login, name='logout'),
  url(r'^accounts/', include('accounts.urls')),
  url(r'^audio/', include('audio.urls', namespace='audio')),
  url(r'^dailybread/', include('dailybread.urls', namespace="dailybread")),
  url(r'^badges/', include('badges.urls', namespace="badges")),
  url(r'^schedules/', include('schedules.urls', namespace="schedules")),
  url(r'^attendance/', include('attendance.urls', namespace="attendance")),
  url(r'^leaveslips/', include('leaveslips.urls', namespace="leaveslips")),
  url(r'^verse_parse/', include('verse_parse.urls', namespace="verse_parse")),
  url(r'^meal_seating/', include('meal_seating.urls')),
  url(r'^absent_trainee_roster/', include('absent_trainee_roster.urls', namespace="absent_trainee_roster")),
  url(r'^syllabus/', include('syllabus.urls', namespace="syllabus")),
  url(r'^classnotes/', include('classnotes.urls', namespace="classnotes")),
  url(r'^classes/', include('classes.urls', namespace="classes")),
  url(r'^lifestudies/', include('lifestudies.urls', namespace="lifestudies")),
  url(r'^seating/', include('seating.urls', namespace='seating')),
  url(r'^exams/', include('exams.urls', namespace="exams")),
  url(r'^web_access/', include('web_access.urls', namespace="web_access")),
  url(r'^apimport/', include('apimport.urls', namespace="apimport")),
  url(r'^bible_tracker/', include('bible_tracker.urls', namespace='bible_tracker')),
  url(r'^announcements/', include('announcements.urls', namespace='announcements')),
  url(r'^services/', include('services.urls', namespace="services")),
  url(r'^semi/', include('semi.urls', namespace="semi")),
  url(r'^house_requests/', include('house_requests.urls', namespace="house_requests")),
  url(r'^hc/', include('hc.urls', namespace="hc")),
  url(r'^room_reservations/', include('room_reservations.urls', namespace="room_reservations")),
  url(r'^graduation/', include('graduation.urls', namespace="graduation")),
  url(r'^xb/', include('xb_application.urls', namespace="xb")),
  url(r'^interim/', include('interim.urls', namespace="interim")),
  # admin urls
  url(r'^adminactions/', include('adminactions.urls')),  # django-adminactions pluggable app
  url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
  url(r'^admin/', include(admin.site.urls)),
  url(r'^admin/', include("massadmin.urls")),
  url(r'^static/(?P<path>.*)$', django.views.static.serve, {'document_root': settings.STATIC_ROOT}),
  # fobi urls
  # DB Store plugin URLs
  url(r'^fobi/plugins/form-handlers/db-store/', include('fobi.contrib.plugins.form_handlers.db_store.urls')),
  url(r'^fobi/plugins/form-wizard-handlers/db-store/', include('fobi.contrib.plugins.form_handlers.db_store.urls.form_wizard_handlers')),
  # View URLs
  url(r'^forms/', include('fobi.urls.view')),
  # Edit URLs
  url(r'^forms/', include('fobi.urls.edit')),
  url(r'^404/$', custom404errorview),  # for development
  url(r'^500/$', custom500errorview),  # for development
  url(r'^503/$', custom503errorview),  # for development
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

router = BulkRouter()
router.register(r'users', UserViewSet)
router.register(r'trainees', TraineeViewSet, base_name='trainees')
router.register(r'events', EventViewSet)
router.register(r'allevents', AllEventViewSet, base_name='allevents')
router.register(r'schedules', ScheduleViewSet)
router.register(r'allschedules', AllScheduleViewSet, base_name='allschedules')
router.register(r'rolls', RollViewSet)
router.register(r'allrolls', AllRollViewSet, base_name='allrolls')
router.register(r'individualslips', IndividualSlipViewSet)
router.register(r'allindividualleaveslips', AllIndividualSlipViewSet, base_name='allindividualslips')
router.register(r'groupslips', GroupSlipViewSet)
router.register(r'allgroupslips', AllGroupSlipViewSet, base_name='allgroupslips')
router.register(r'books', BooksViewSet)
router.register(r'summaries', DisciplineSummariesViewSet)
router.register(r'attendance', AttendanceViewSet)
router.register(r'allattendance', AllAttendanceViewSet, base_name='allattendance')
router.register(r'audio', AudioRequestViewSet)
router.register(r'charts', ChartViewSet)
router.register(r'seats', SeatViewSet)
router.register(r'partials', PartialViewSet)
router.register(r'terms', TermViewSet)
router.register(r'classnotes', ClassNoteViewSet)
router.register(r'update-workers', UpdateWorkersViewSet, base_name='updateworkers')
router.register(r'update-workloads', ServiceSlotWorkloadViewSet, base_name='updateworkload')
router.register(r'update-active-services', ServiceActiveViewSet, base_name='updateservice')
router.register(r'update-time-services', ServiceTimeViewSet, base_name='updatetime')
router.register(r'update-exception-active', ExceptionActiveViewSet)
router.register(r'service-assignments', AssignmentViewSet, base_name='serviceassignments')
router.register(r'service-assignments-pin', AssignmentPinViewSet)
router.register(r'tables', TableViewSet)

attendance_router = routers.NestedSimpleRouter(router, r'attendance', lookup='attendance')
attendance_router.register(r'rolls', RollViewSet, base_name='rolls')
rolls_router = routers.NestedSimpleRouter(attendance_router, r'rolls', lookup='rolls')
attendance_router.register(r'events', EventViewSet, base_name='events')
events_router = routers.NestedSimpleRouter(attendance_router, r'events', lookup='events')
attendance_router.register(r'schedules', ScheduleViewSet, base_name='schedules')
schedules_router = routers.NestedSimpleRouter(attendance_router, r'schedules', lookup='schedules')
attendance_router.register(r'individualslips', IndividualSlipViewSet, base_name='individualslips')
leaveslips_router = routers.NestedSimpleRouter(attendance_router, r'individualslips', lookup='individualslips')
attendance_router.register(r'groupslips', GroupSlipViewSet, base_name='groupslips')
groupleaveslips_router = routers.NestedSimpleRouter(attendance_router, r'groupslips', lookup='groupslips')

urlpatterns += [
  url(r'^api/trainees/gender/(?P<gender>[BS])/$', TraineesByGender.as_view()),
  url(r'^api/trainees/term/(?P<term>[1234])/$', TraineesByTerm.as_view()),
  url(r'^api/trainees/team/(?P<pk>\d+)/$', TraineesByTeam.as_view()),
  url(r'^api/trainees/teamtype/(?P<type>\w+)/$', TraineesByTeamType.as_view()),
  url(r'^api/trainees/house/(?P<pk>\d+)/$', TraineesByHouse.as_view()),
  url(r'^api/trainees/locality/(?P<pk>\d+)/$', TraineesByLocality.as_view()),
  url(r'^api/trainees/hc/$', TraineesHouseCoordinators.as_view()),
  url(r'^api/', include(router.urls, namespace='rest_framework')),
  url(r'^api/', include(attendance_router.urls)),
  # third party
  url(r'^docs/', get_swagger_view(title='DJAttendance API documentation')),
  url(r'^explorer/', include('explorer.urls')),
  url(r'^select2/', include('django_select2.urls')),
]

urlpatterns += staticfiles_urlpatterns()
if settings.DEBUG:
  import debug_toolbar
  urlpatterns += [
    url(r'^__debug__/', include(debug_toolbar.urls)),
  ]

urlpatterns += [
  url(r'^notifications/', get_nyt_pattern()),
  url(r'wiki', get_wiki_pattern())
]

handler404 = 'ap.views.custom404errorview'  # if settings.DEBUG = FALSE
handler500 = 'ap.views.custom500errorview'  # if settings.DEBUG = FALSE
handler503 = 'ap.views.custom503errorview'  # if settings.DEBUG = FALSE

ap/audio/urls.py
from django.conf.urls import url

from . import views

app_name = 'audio'

urlpatterns = [
    url(r'^list/$', views.AudioHome.as_view(), name='audio-home'),
    url(r'^upload/$', views.AudioCreate.as_view(), name='audio-upload'),
    url(r'^ta-list/$', views.TAAudioHome.as_view(), name='ta-audio-home'),
    url(r'^list/(?P<week>\d+)$', views.AudioHome.as_view(), name='audio-home-week'),
    url(r'^request/$', views.AudioRequestCreate.as_view(), name='audio-request'),
    url(r'^update/(?P<pk>\d+)$', views.AudioRequestUpdate.as_view(), name='audio-update'),
    url(r'^(?P<status>[APFDS])/(?P<id>\d+)$', views.modify_status, name='modify-status'),
    url(r'^ta-comment/(?P<pk>\d+)$', views.TAComment.as_view(), name='ta-comment'),
]

ap/classnotes/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
  url(r'^$', views.ClassnotesListView.as_view(), name='classnotes_list'),
  url(r'^classnotes-assign$', views.ClassnotesAssignView.as_view(), name='classnotes_assign'),
  url(r'^classnotes-create$', views.ClassnotesCreateView.as_view(), name='classnotes_create'),
  url(r'^classnotes-report$', views.ClassnotesReportView.as_view(), name='classnotes_report'),
  url(r'^classnotes-single-trainee$', views.ClassnotesSingleTraineeView.as_view(), name='classnotes_single_trainee'),
  url(r'^(?P<pk>\d+)/detail-classnotes$', views.ClassnotesUpdateView.as_view(), name='classnotes_detail'),
  url(r'^(?P<pk>\d+)/approve-classnotes$', views.ClassnotesApproveView.as_view(), name='classnotes_approve'),
]

ap/audio/forms.py
from django import forms

from aputils.trainee_utils import is_TA
from terms.models import Term
from .models import AudioRequest, AudioFile, order_audio_files


class AudioRequestForm(forms.ModelForm):
  class Meta:
    model = AudioRequest

    fields = (
        'trainee_comments',
        'audio_requested',
        'TA_comments'
    )

    labels = {
        'trainee_comments': 'Please describe the reason for your request in detail.',
    }

  def __init__(self, *args, **kwargs):
    self.user = kwargs.pop('user')
    super(AudioRequestForm, self).__init__(*args, **kwargs)
    sorted_files = order_audio_files(AudioFile.objects.filter_term(Term.current_term()))
    choices = [(a.id, a.request_title) for a in sorted_files]
    self.fields['audio_requested'].widget.attrs['class'] = 'select-fk'
    self.fields['audio_requested'].choices = choices
    if not is_TA(self.user):
      self.fields['TA_comments'].disabled = True
      if self.instance.id and self.instance.status in ['A', 'D']:
        self.fields['trainee_comments'].disabled = True
        self.fields['audio_requested'].disabled = True


class AudioRequestTACommentForm(forms.ModelForm):
  class Meta:
    model = AudioRequest
    fields = ['TA_comments']

ap/audio/views.py
import json
import os
from datetime import date
from itertools import chain

from aputils.trainee_utils import trainee_from_user, is_trainee
from aputils.utils import modify_model_status
from braces.views import GroupRequiredMixin
from django.conf import settings
from django.core.urlresolvers import reverse_lazy
from django.forms import ValidationError
from django.http import HttpResponseBadRequest, JsonResponse
from django.views import generic
from rest_framework_bulk import BulkModelViewSet
from terms.models import Term

from .forms import AudioRequestForm, AudioRequestTACommentForm
from .models import AudioFile, AudioRequest, fs, valid_audiofile_name
from .serializers import AudioRequestSerializer


def import_audiofiles():
  term_folder = settings.AUDIO_FILES_ROOT
  if not os.path.exists(term_folder):
    return
  files = os.listdir(term_folder)
  imported = set([a.audio_file.name for a in AudioFile.objects.all()])
  for f in files:
    if fs.get_valid_name(f) in imported or not valid_audiofile_name(f):
      continue
    audio = AudioFile()
    try:
      audio.audio_file.name = fs.get_valid_name(f)
      audio.save()
    except ValidationError:
      pass


class AudioHome(generic.ListView):
  model = AudioFile
  template_name = 'audio/audiofile_list.html'

  def dispatch(self, request, week=None, *args, **kwargs):
    import_audiofiles()
    term = Term.current_term()
    current_week = term.term_week_of_date(date.today())
    if not week:
      week = current_week
    self.week = int(week)
    date_format = '%m/%d/%Y'
    self.weeks = json.dumps(map(
        lambda w: {
            'id': w,
            'text': 'Week {0}: {1} - {2}'.format(
                w,
                term.startdate_of_week(w).strftime(date_format),
                term.enddate_of_week(w).strftime(date_format)
            )
        }, range(current_week + 1)
    ))
    return super(AudioHome, self).dispatch(request, *args, **kwargs)

  def get_queryset(self):
    trainee = trainee_from_user(self.request.user)
    files = AudioFile.objects.filter_list(self.week, trainee)
    attendance_record = trainee.attendance_record
    for f in files:
      # replace methods with computed values because trainee can't be passed in template
      f.classnotes = f.classnotes(trainee)
      f.request = f.request(trainee)
      f.has_leaveslip = f.has_leaveslip(trainee, attendance_record)
      f.can_download = f.can_download(f.request, f.has_leaveslip)
    return files


class TAAudioHome(generic.ListView):
  model = AudioRequest
  template_name = 'audio/audio_request_list.html'

  def get_queryset(self):
    qs = AudioRequest.objects.filter_term(Term.current_term())
    qs = qs.filter(status='P') | qs.filter(status='F')
    return qs.order_by('date_requested')

  def get_context_data(self, **kwargs):
    context = super(TAAudioHome, self).get_context_data(**kwargs)
    audio_requests = AudioRequest.objects.none()
    reqs = AudioRequest.objects.filter_term(Term.current_term()).order_by('date_requested')
    for status in ['P', 'F', 'A', 'D']:
      audio_requests = chain(audio_requests, reqs.filter(status=status))
    context['audio_requests'] = audio_requests
    return context


class TAComment(GroupRequiredMixin, generic.UpdateView):
  model = AudioRequest
  template_name = 'requests/ta_comments.html'
  form_class = AudioRequestTACommentForm
  group_required = ['training_assistant']
  raise_exception = True
  success_url = reverse_lazy('audio:ta-audio-home')

  def get_context_data(self, **kwargs):
    context = super(TAComment, self).get_context_data(**kwargs)
    context['item_name'] = AudioRequest._meta.verbose_name
    context['request'] = self.get_object()
    return context


modify_status = modify_model_status(AudioRequest, reverse_lazy('audio:ta-audio-home'))


class AudioRequestCreate(generic.CreateView):
  model = AudioRequest
  template_name = 'requests/request_form.html'
  form_class = AudioRequestForm
  success_url = reverse_lazy('audio:audio-home')

  def get_form_kwargs(self):
    kwargs = super(AudioRequestCreate, self).get_form_kwargs()
    kwargs.update({'user': self.request.user})
    return kwargs

  def form_valid(self, form):
    req = form.save(commit=False)
    req.trainee_author = trainee_from_user(self.request.user)
    req.save()
    return super(AudioRequestCreate, self).form_valid(form)


class AudioCreate(generic.CreateView):
  template_name = 'audio/audiofile_upload.html'
  model = AudioFile
  fields = []

  def post(self, request):
    uploaded = request.FILES['file']
    audio_file = AudioFile(audio_file=uploaded)
    try:
      audio_file.save()
      return JsonResponse({'status': 'ok'})
    except ValidationError:
      return HttpResponseBadRequest('File name format incorrect.')


class AudioRequestUpdate(AudioRequestCreate, generic.UpdateView):
  def get_context_data(self, **kwargs):
    context = super(AudioRequestUpdate, self).get_context_data(**kwargs)
    if is_trainee(self.request.user):
      if context['form'].instance.status in ['D', 'A']:
        context['read_only'] = True
    return context


class AudioRequestViewSet(BulkModelViewSet):
  queryset = AudioRequest.objects.all()
  serializer_class = AudioRequestSerializer

ap/audio/templates/audio/audio_player.html
<head>
<style>
.audio-player {
  position: fixed;
  bottom: 0;
  left: 0;
  width: 100%;
  z-index: 1000;
}

.audio-player .mejs__controls {
  margin-bottom: 5px;
  background: none;
}

.audio-player .mejs__speed-selector {
  height: 150px;
}

.audio-player .mejs__container {
  background-color: #095F80;
}
</style>

<script>
class AudioPlayer {
  constructor($elem) {
    let elem = $elem.mediaelementplayer({
      audioHeight: '50',
      audioWidth: '100%',
      audioVolume: 'vertical',
      features: ['playpause', 'current', 'progress', 'duration', 'volume', 'speed',],
    })[0];
    this.audioElement = elem;

    if ($(this.audioElement).find('source').length != 0) {
      this.show();
    }
  }

  playAudio(src) {
    let audio = $(this.audioElement);
    audio.attr('src', src);
    this.audioElement.load();
    this.audioElement.play();
  }

  show() {
    $('.audio-player').css({'display': 'auto'});
  }
}

$(document).ready(() => {
  let player = new AudioPlayer($('#player'));
});
</script>
</head>

<div class="audio-player">
  <audio id="player" controls autoplay>
    {% for audio in object_list %}
      <source src="{{ audio.audio_file.url }}" title="{{ audio.event.name }}" type="audio/mp3"></source>
    {% endfor %}
  </audio>
</div>

ap/audio/templates/audio/audio_request_detail.html
{% if audiofile.has_leaveslip %}
  <i>Leave slip approved</i>
{% else %}
  Date requested: {{ audiofile.request.date_requested }}<br>
  Status: {{ audiofile.request.get_status_display }}<br>
  Reason: {{ audiofile.request.trainee_comments }}
  {% if audiofile.request.TA_comments %}
    <br>
    TA comments: {{ audiofile.request.TA_comments }}
  {% endif %}
{% endif %}
{% if audiofile.can_download %}
  <br>
  <a href="{{ audiofile.audio_file.url }}" class="btn btn-primary download-link" download>
    <span class="glyphicon glyphicon-download-alt"></span>
    Download file
  </a>
  <p></p>
  <b>After listening, please delete the audio file.</b>
{% endif %}
{% if audiofile.request.status == 'P' %}
  <br>
  <a href="{% url 'audio:audio-update' pk=audiofile.request.id %}" class="btn btn-default download-link">
    <span class="glyphicon glyphicon-pencil"></span>
    Edit request
  </a>
{% endif %}

ap/audio/templates/audio/audio_request_list.html
{% extends "requests/request_list.html" %}
{% load common_tags %}

{% block scripts %}
{{ block.super }}
<script type="text/javascript">
  $(document).ready(function(){
    $("#id_audio_request_table").DataTable({
      info: false,
      paging: false,
      dom: '<"row"<"col-sm-6"Bl><"col-sm-6"f>>' +
      '<"row"<"col-sm-12"<"table-responsive"tr>>>' +
      '<"row"<"col-sm-5"i><"col-sm-7"p>>',
      columnDefs: [
        {
          "targets": 0,
          "visible": false,
          "searchable": false,
        }
      ]
    })
  });
</script>
{% endblock %}

{% block tables %}
{% ifusergroup training_assistant %}
<div class="data-table-container">
  <table id="id_audio_request_table" class="table table-striped table-bordered">
    <thead>
      <tr>
        <th>Count</th>
        <th>Name</th>
        <th>Submitted</th>
        <th>Description</th>
        <th>Status</th>
        <th>View</th>
      </tr>
    </thead>
    <tbody>
      {% for req in audio_requests %}
      <tr>
        <td>{{forloop.counter}}</td>
        <td>{{req.requester_name}}</td>
        <td>{{req.date_requested}}</td>
        <td>{{req.trainee_comments|truncatechars:100}}</td>
        <td>{{req.status}}</td>
        <td><a href="{{ req.get_absolute_url }}">Detail</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endifusergroup %}
{% endblock %}

ap/audio/templates/audio/audiofile_detail.html
<div class="col-sm-6">
  <div class="panel panel-default audio-item" src="{{ audiofile.audio_file.url }}">
    <div class="panel-heading">
      <div class="row">
        <div class="col-xs-11">
          {{audiofile.list_title }}
          <span class="pull-right">
            {% for s in audiofile.speakers %}
              {{ s }}{% if not forloop.last %}, {% endif %}
            {% endfor %}
          </span>
          <div class="panel-heading-date">{{ audiofile.date }}</div>
        </div>
        <div class="col-xs-1">
          {% if audiofile.request or audiofile.has_leaveslip %}
            <span class="glyphicon glyphicon-download-alt download-button
              {% if audiofile.can_download %}download-approved{% endif %}
              {% if audiofile.request.status == 'P' %}download-pending{% endif %}
              {% if audiofile.request.status == 'D' %}download-denied{% endif %}">
            </span>
          {% endif %}
          {% if audiofile.classnotes %}
            <a target="_blank"
               href="{% url 'classnotes:classnotes_detail' pk=audiofile.classnotes.id %}"
               class="classnotes-button">
              <i class="glyphicon glyphicon-book"></i>
            </a>
          {% endif %}
        </div>
      </div>
    </div>
    <div class="panel-body">
      {% include 'audio/audio_request_detail.html' %}
    </div>
  </div>
</div>

ap/audio/templates/audio/audiofile_list.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}Audio Files{% endblock %}

{% block references %}
  <link href="{% static 'audio/css/audiofile_list.css' %}" rel="stylesheet" type="text/css">
  <style>
  #recording-list {
    padding-bottom: 40px;
  }
  </style>
{% endblock %}

{% block scripts %}
  <script>
    let WEEKS = {{ view.weeks | safe }};
    let WEEK = {{ view.week }};
    let AUDIO_LIST_URL = "{% url 'audio:audio-home-week' week=999 %}";
    let URL_PLACEHOLDER = '999';
  </script>
  <script src="{% static 'audio/js/audiofile_list.js' %}"></script>
{% endblock %}

{% block content %}
{% include "audio/audio_player.html" %}

<div class="row">
  <div class="col-md-3">
    <h2 id="page-title">Audio Recording List</h2>
  </div>
  <div id="week-select-container" class="col-md-3">
    <select id="week-select"></select>
  </div>
  <div id="request-link" class="col-md-3">
    <a href="{% url 'audio:audio-request' %}" class="btn btn-primary">Make an audio file download request</a>
  </div>
</div>

<div id="recording-list" class="row">
  {% for audiofile in object_list %}
    {% include 'audio/audiofile_detail.html' %}
  {% empty %}
    <div class="col-xs-12"><i>No audio recordings available for this week.</i></div>
  {% endfor %}
</div>

{% endblock %}

ap/audio/templates/audio/audiofile_upload.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}Audio Upload{% endblock %}

{% block content %}
  <div class="well">
    <h3 style="margin-top:0px;">Audio File Upload</h3>
    <p>
      Upload files with the name in standard format:
      <code>B1-01 2017-03-02 DSady.mp3</code>
    </p>
    <p>
      Or for pre-training classes:
      <code>PT-00 2017-02-18 An Opening Word DHigashi.mp3</code>
    </p>
    <ul>
      <li><code>B1</code> is the class code</li>
      <li><code>01</code> is the week number</li>
      <li><code>2017-03-02</code> is the date, in year-month-day format</li>
      <li><code>DSady</code> is the speaker</li>
      <li><code>An Opening Word</code> is the pre-training class title</li>
    </ul>
  </div>
  <form class="dropzone" action="{% url "audio:audio-upload" %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
  </form>
{% endblock %}

ap/audio/templates/audio/ta_buttons.html
<a href="{% url 'audio:modify-status' status='A' id=request.id %}">
  <button class="btn btn-success approve" title="Approve"><span class="glyphicon glyphicon-ok"></span></button>
</a>
 <a href="{% url 'audio:modify-status' 'D' request.id %}">
  <button class="btn btn-danger deny" title="Deny"><span class="glyphicon glyphicon-remove"></span></button>
</a>
{% if not 'Fellowship' in request.get_status_display %}
   <a href="{% url 'audio:modify-status' 'F' request.id %}">
    <button class="btn btn-info fellowship" title="Mark for Fellowship"><span class="glyphicon glyphicon-exclamation-sign"></span></button>
  </a>
{% endif %}
<a href ="{% url 'audio:ta-comment' request.id %}">
  <button class="btn btn-info comment" title="Comment"><span class="glyphicon glyphicon-comment"></span></button>
</a>

ap/audio/templates/audio/ta_detail.html
Comments: {{ request.trainee_comments }}<br>